version: 0.2

env:
  variables:
    AWS_REGION: "eu-north-1"
    REPO_NAME: "travelease-booking"

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 904233121598.dkr.ecr.$AWS_REGION.amazonaws.com)

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPO_NAME .
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - docker tag $REPO_NAME:latest 904233121598.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 904233121598.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
