version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies (if any)..."
      # Agar koi frontend dependencies hain toh daal sakte ho, jaise npm install
  build:
    commands:
      - echo "Building frontend and injecting ALB URL..."
      # $ALB_DNS_NAME ek environment variable hai jo hum CodeBuild mein daalenge
      - sed -i "s|__ALB_DNS_PLACEHOLDER__|$ALB_DNS_NAME|g" index.html
  post_build:
    commands:
      - echo "Copying static assets to build directory..."
      - # Yahan additional static assets ko build directory mein copy karne ka command daal sakte hain
artifacts:
  files:
    - '**/*' # Saari files ko S3 par deploy karne ke liye