services:
  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123

  booking:
    build:
      context: ../Booking_Service
    ports:
      - "5000:5000"

  flight:
    build:
      context: ../Flight_Service
    ports:
      - "5002:5002"

  payment:
    build:
      context: ../Payment_Service
    ports:
      - "5003:5003"
