scrape_configs:
  - job_name: 'booking'
    static_configs:
      - targets: ['travelease-ALB-1552174703.eu-north-1.elb.amazonaws.com/book/metrics']

  - job_name: 'flight'
    static_configs:
      - targets: ['travelease-ALB-1552174703.eu-north-1.elb.amazonaws.com/flight/metrics']

  - job_name: 'payment'
    static_configs:
      - targets: ['travelease-ALB-1552174703.eu-north-1.elb.amazonaws.com/pay/metrics']
