global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'booking-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['booking-service:5000']

  - job_name: 'flight-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['flight-service:5002']

  - job_name: 'payment-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['payment-service:5003']
