scrape_configs:
  - job_name: 'booking'
    static_configs:
      - targets: ['booking-1:5000']

  - job_name: 'flight'
    static_configs:
      - targets: ['flight-1:5002']

  - job_name: 'payment'
    static_configs:
      - targets: ['payment-1:5003']
