global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'booking'
    static_configs:
      - targets: ['host.docker.internal:5000']
  - job_name: 'flight'
    static_configs:
      - targets: ['host.docker.internal:5002']
  - job_name: 'payment'
    static_configs:
      - targets: ['host.docker.internal:5003']
