global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'booking'
    static_configs:
      - targets: ['booking:5000']

  - job_name: 'flight'
    static_configs:
      - targets: ['flight:5002']

  - job_name: 'payment'
    static_configs:
      - targets: ['payment:5003']

  - job_name: 'cloudwatch'
    metrics_path: /metrics
    static_configs:
      - targets: ['cloudwatch-exporter:9106']
